name: impresion_zebra
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.2
  flutter_blue_plus: ^1.35.2
  esc_pos_utils_plus: ^2.0.2
  printing: ^5.14.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  path: ^1.9.0
  zsdk: ^3.2.0+3
  # esc_pos_printer_plus: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

